# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef585ab9df99167348ef83793a88b00939a4ba1e853fad0b31b427f45972a52b8d634c61b25178e490cc6528e3ad122f0a31ce450772fbaa52a0e86ec3bfe821

test:
  secret_key_base: 5305afacc17c2f6929d38d39fd2dbfd0eb61e26eea380779aa333646bcd26cae3d1520af181efe0a8c363edc795e7d5c5e0390b0784738368fc0a9a830ee0288

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
